- name: Modify CPU and memory for a VM
  hosts: localhost

  tasks:
    - name: Modify VM's CPU and Memory
      redhat.openshift.k8s:
        state: present
        template: templates/vm-cpumem.yml
