- name: Add a new NIC to VM
  hosts: localhost

  tasks:
    - name: Add a new network interface card into the VM 
      redhat.openshift.k8s:
        state: present
        template: templates/add-nic.yml
