- name: Take a snapshot for a VM
  hosts: localhost

  tasks:
    - name: Login to OpenShift
      redhat.openshift.openshift_auth:
        host: "{{ openshift_fqdn }}"
        username: "{{ openshift_user }}"
        password: "{{ openshift_password }}"
        validate_certs: false
      register: openshift_auth_results

    - name: Print authentication rsults
      ansible.builtin.debug:
        var: openshift_auth_results

    - name: Take the snapshot
      redhat.openshift.k8s:
        api_key: "{{ openshift_auth_results.openshift_auth.api_key }}"
        host: "{{ openshift_fqdn }}"
        validate_certs: false
        state: present
        template: templates/vm-snapshot.yml
