- name: Restore a snapshot for a VM
  hosts: localhost

  tasks:
    - name: Restore VM from one existing snapshot
      redhat.openshift.k8s:
        state: present
        template: templates/restore-snapshot.yml
