apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: "{{ vm_name }}"
  namespace: "{{ vm_namespace }}"
spec:
  dataVolumeTemplates:
    - apiVersion: cdi.kubevirt.io/v1beta1
      kind: DataVolume
      metadata:
        creationTimestamp: null
        name: "{{ vm_name }}"
      spec:
        sourceRef:
          kind: DataSource
          name: rhel9
          namespace: openshift-virtualization-os-images
        storage:
          resources:
            requests:
              storage: "{{ vm_storage }}"
  running: false
  template:
    metadata:
      labels:
        app: "{{ vm_name }}"
    spec:
      architecture: amd64
      domain:
        cpu:
          cores: {{ vm_cpu_cores }}
          sockets: 1
          threads: 1
        devices:
          disks:
            - disk:
                bus: virtio
              name: rootdisk
            - disk:
                bus: virtio
              name: cloudinitdisk
          interfaces:
            - masquerade: {}
              model: virtio
              name: default
          rng: {}
        machine:
          type: pc-q35-rhel9.4.0
        memory:
          guest: "{{ vm_memory }}"
        resources: {}
      networks:
        - name: default
          pod: {}
      terminationGracePeriodSeconds: 180
      volumes:
        - dataVolume:
            name: "{{ vm_name }}"
          name: rootdisk
        - cloudInitNoCloud:
            userData: |-
              #cloud-config
              ssh_pwauth: true
              user: "{{ vm_user }}"
              password: "{{ vm_passwd }}"
              chpasswd: { expire: False }
          name: cloudinitdisk
